# Generated by Django 2.1.7 on 2019-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190320_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
